import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import Link from 'next/link'
  
const ff = Raleway({ subsets: ['latin'] })
const timeZone = 'Europe/London'

export const metadata: Metadata = {
  title: 'BuzzLines - join the buzz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ff.className}>
        <header className='bg-black text-white'>
          <div className='flex'>
            <svg xmlns="http://www.w3.org/2000/svg" className="w-10 text-yellow-400" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
            </svg>
            <span className='text-5xl'>BuzzLines</span>
          </div>
          <nav className='flex justify-start'>
            <Link href={'/'} className=''>Home</Link>
            <Link href={'/stops'} className='mx-8'>Stops</Link>
            <Link href={'/about'}>About</Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer className='fixed bottom-1 right-1 text-xs'>
          <div>&copy; 2023 BuzzLines</div>
        </footer>
      </body>
    </html>
  )
}
